# -*- coding: utf-8 -*-
"""3pm_Group19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A8VytQ6SgaihCplmi728oz0y5LsY3rqw

#The data was downloaded from: https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import folium as fl
import plotly.express as px
import folium
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df_rawdata = pd.read_csv('/content/drive/My Drive/Life Expectancy Data.csv')
df_rawdata

"""**Attribute Definitions**
**Status: Developed or Developing
**Life Expectancy: by age
**Adult Mortality: Mortality rates of both sexes ages 15-60 per 1000 population
**Infant Mortality: infant deaths per 1000 population
**Alcohol: consumption (15+) per capita, liters of pure alcohol
**Percentage Expenditure: percentage of gdp per capita spent on health
**Hepatitis B: percentage of HepB immunization amongst 1 year olds 
**Measles: reported cases per 1000 population
**BMI: average BMI of population
**Under five deaths: deaths of people under 5 years old per 1000 population
**Polio:percentage of polio immunization amongst 1 year olds
**Total Expenditure: Government expenditure on health as a percentage of total gov expenditure
**Diptheria: Immunization (DTP3) among 1 y/o, percentage
**HIV/AIDS: deaths per 1000 live births
**GDP: GDP per capita in USD
**Population: population of the country
**thinness 1-19: prevalence of thinness ages 10 to 19, percentage
**thinness 5-9: prevalence of thinness ages 5 to 9, percentage
**Income composition of resources: human development index in terms of income composition of resources (index from 0 to 1)
**Schooling: average number of years of schooling

"""

df_trdata = df_rawdata.transpose()

df_who = df_trdata.transpose()
df_who

"""Lets look at a macro view of how countries compare on a map to see if there are any regional trends for life expectancy"""

! wget --quiet https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/world_countries.json

world_geo = 'world_countries.json'

world_map = folium.Map(location=[0,0], zoom_start=2)

world_map.choropleth(
    geo_data = world_geo,
    data = df_who,
    columns = ['Country', 'Life expectancy '],
    key_on = 'feature.properties.name',
    fill_color = 'YlOrRd',
    hover_name = 'Country',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Global Life Expectancy')

world_map

"""There seems to be a correlation between life expectency and the western civilizations. Lets take a closer look at some of those countries

What is the connection between Life Expectancy and GDP data?
"""

df = pd.DataFrame(df_who, columns=['Life expectancy ','GDP'])
df.plot(x='Life expectancy ',y='GDP', kind='scatter',figsize=(9,6), title='Correlation of Life Expectancy with GDP')
plt.show()

"""This plot shows that a higher GDP per capita increases the odds of a higher life expectancy. While there are some countries with a lower GDP per capita that have a higher life expectancy, none of the countries with a higher GDP per capita have a lower life expectancy

What is the correlation between BMI and life expectancy
"""

df = pd.DataFrame(df_who, columns=['Life expectancy ',' BMI '])
df.plot(x='Life expectancy ',y=' BMI ', kind='scatter',figsize=(9,6), title='Correlation of Life Expectancy with BMI')
plt.show()

"""Now this shows us that BMI is also correlated with higher life expectancy. While it is not a direct cause for higher life expectancy, we can see that almost all of the countries with higher BMI have a higher life expectancy"""

df_who2015 = df_who.query('Year==2015')

"""We could not find an efficient way to take the average values over the years for each country without creating a new dataframe for all 193 countries, so we will use the data from the year 2015 since it is the most recent"""

df_2015sorted = df_who2015.sort_values(by=['Life expectancy '],ascending=False)

df_2015top10 = df_2015sorted.head(10)

"""Creating a list of the top 10 highest life expectancies by country"""

df_2015bottom10 = df_2015sorted.tail(10)

"""Creating a list of the 10 lowest life expectancies by country"""

df_2015top10

px.bar(df_2015top10, y='Life expectancy ', x='Country',hover_name='Life expectancy ',color='GDP', title='A Look at the Top 10 Countries by Life Expectancy')

"""Here we can see what the top 10 countries by life expectancies are majority western countries, and several of the remaining countries have a mixture of western influence in thier history and development

Lets format the data frame to include just Western countries, chosen by random, to see how they compare the the average
"""

df_fix = df_who.set_index('Country')

df_fix2 = df_fix.transpose()

df_fix3 = df_fix2[['Sweden','Australia','Germany','France','Canada','Switzerland','Norway','Spain','Italy','Portugal']]

df_west = df_fix3.transpose()

df_west

df_west.drop(['percentage expenditure','Status',' thinness  1-19 years',' thinness 5-9 years','Alcohol','infant deaths','Hepatitis B','Measles ','under-five deaths ','Polio','Total expenditure',' HIV/AIDS','Diphtheria ','Income composition of resources'],axis=1, inplace=True)

df_west

df_newWest = df_west.reset_index()

df_newWest

df_newWest2015 = df_newWest.query('Year==2015')
df_newWest2015

"""Now lets make a sunburst plot of the 10 Western countries to visualize BMI and GDP"""

fig = px.sunburst(df_newWest2015, values=' BMI ', path=['Country', 'GDP',' BMI '], hover_name='GDP', color='Life expectancy ',title='10 Western Countries Selected at Random')
fig.update_layout(title_x=0.48)
fig.show()

"""From this sunburst model you can see that all of these western countries have similar BMI since the size of the slice is similar; the life expectancy does not vary much between the countries since the range is within only a few years. It should also be noted that the BMI of all of these countries is very high"""

df_2015top10

"""Now lets create a similar sunburst plot to compare the top 10 countries based on life expectancy in general"""

fig = px.sunburst(df_2015top10, values=' BMI ', path=['Country', 'GDP',' BMI '], hover_name='GDP', color='Life expectancy ',title='Top 10 Countries by Life Expectancy and BMI/GDP')
fig.update_layout(title_x=0.48)
fig.show()

"""From the sunburst of the top 10 highest life expectancy overall, we can see that BMI fluctuates much more and the life expectancy also fluctuates a little more. We also see that the highest life expectancy has a very low BMI compared to the others. It is also, however important to note that the BMI of the country with the higest life expectancy is only 6.1, which is well under what is considered a healthy BMI. This implies that while the highest life expectancy is in Slovenia, the BMI average is at an unhealthy level. This plot still supports the general idea that higher BMI and Western developed countries have higher life expectancy"""

df_2015bottom10

"""Now to create a sunburst plot to compare the same idea for the lowest life expectancy countries."""

fig = px.sunburst(df_2015bottom10, values=' BMI ', path=['Country', 'GDP'], hover_name='GDP', color='Life expectancy ',title ='10 Countries with Lowest Life Expectancy with BMI/GDP')
fig.update_layout(title_x=0.48)
fig.show()

"""The country Côte d'Ivoire is missing GDP data, so the BMI values did not show, but the portion sizes of each country on the plot are still based on BMI; so we can see that the BMI's are all in a similar range (the next bar plot will give a visual of the BMI's to show the values). We can see that the life expectancy is drastically lower, with a range from 51 to 57, and most of the GDP values are also much lower than the majority of the higher life expectancy countries"""

px.bar(df_2015bottom10,x='Country',y=' BMI ',title='BMI of 10 Lowest Life Expectancy')

"""This bar chart visualizes the BMI's of each of the countries with the lowest life expectancy to show the values that did not present in the previous graph. As you can see, the BMI values are much lower than the western countries, which had BMI values ranging from 57 to 67

Now we will sort the countries based on their GDP per capita just to see how this directly influences life expectgancy and we will try to visualize the ratio of the GDP's to see if there is a correlation between the ratio of GDP to the ratio of life expectancies
"""

df_gdp = df_who2015.sort_values(by='GDP')

df_gdp20 = df_gdp.head(20)

df_gdp20['GDP'].plot(kind='pie',figsize=(17,10),
                       startangle=90,
                       shadow=True,
                       autopct='%1.1f%%',
                       labels=None,pctdistance=1.05)
plt.title('Top 20 Country GDP per capita')
plt.axis('equal')
plt.legend(labels=df_gdp20['Country'], loc='upper left')
#Show the plot
plt.show()

"""This pie plot shows the top 20 countries by GDP and the pie chart helps to visualize the ratio of how much larger one countries GDP is compared to another

Here we took the top 20 countries by GDP per capita, we can see that very few of them are Western countries
"""

fig = px.sunburst(df_gdp20, values=' BMI ', path=['Country', 'GDP',' BMI '], hover_name='GDP', color='Life expectancy ',title='Top 20 GDP by BMI and Life Expectancy')
fig.update_layout(title_x=0.48)
fig.show()

"""With the same list of top 20 countries by GDP per capita, we have them arranged by BMI and the color indicates life expectancy. This plot makes it easy to see that the higher life expectancies are more correlated with higher BMI's and the top life expectancy countries are the only two from the Western civilization

# Contributions for final project

Bullock: Created Choropleth plot, bar charts, and pie chart. also created power point and assisted other team members with their share.

Khushi & Cyrille: Created Sunburst plots and the code to reshape the dataframe for them.

All team members contributed to interpreting the data and finding insights

Overall contributions: Bullock - 40%, Khushi - 30%, Cyrille - 30%
"""